// <auto-generated />
using System;
using DebitCreditAPI.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DebitCreditAPI.Infra.Data.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20200821100509_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("DebitCreditAPI.Domain.Models.Account", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountNumber");

                    b.Property<decimal>("Balance");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("DebitCreditAPI.Domain.Models.Entry", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DestinyAccountId");

                    b.Property<int>("OriginAccountId");

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.HasIndex("DestinyAccountId");

                    b.HasIndex("OriginAccountId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("DebitCreditAPI.Domain.Models.Entry", b =>
                {
                    b.HasOne("DebitCreditAPI.Domain.Models.Account", "DestinyAccount")
                        .WithMany("DestinyEntries")
                        .HasForeignKey("DestinyAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DebitCreditAPI.Domain.Models.Account", "OriginAccount")
                        .WithMany("OriginEntries")
                        .HasForeignKey("OriginAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
